"""Execution and connection configuration compatibility namespace."""
from config import (
    CONNECT_RETRIES, CONNECT_RETRY_DELAY_SEC, FETCH_RETRIES,
    FETCH_RETRY_BACKOFF_SEC, ORDER_SEND_RETRIES, ORDER_FAIL_QUARANTINE_CYCLES,
    RECONNECT_TIMEOUT_SEC, CF_403_BACKOFF_SEC,
    HEALTHCHECK_RECONNECT_RETRIES, MAX_CONSECUTIVE_RECONNECT_FAILURES,
    MAX_RECONNECT_BACKOFF_SEC, RECONNECT_BACKOFF_BASE_SEC,
    EDIFICIO_ACCOUNT_TYPE, EDIFICIO_SEND_ORDERS_ENABLED, EDIFICIO_ALLOW_REAL,
    EDIFICIO_ORDER_AMOUNT, EDIFICIO_ORDER_DURATION_SEC, EDIFICIO_MAX_ORDER_TRIES,
)
