"""Risk and bankroll configuration compatibility namespace."""
from config import (
    MAX_LOSS_SESSION, CYCLE_MAX_OPERATIONS, CYCLE_TARGET_WINS,
    CYCLE_TARGET_PROFIT_PCT, MASSANIELLO_OPERATIONS,
    MASSANIELLO_EXPECTED_WINS, SESSION_MAX_MIN, SESSION_COOLDOWN_MINUTES,
    RISK_MANAGER, MASSANIELLO_VIRTUAL_CAPITAL,
)
