"""Strategy and market-analysis configuration compatibility namespace."""
from config import (
    USE_DYNAMIC_ATR_RANGE, ATR_PERIOD, ATR_RANGE_FACTOR,
    MIN_DYNAMIC_RANGE_PCT, MAX_DYNAMIC_RANGE_PCT,
    H1_CONFIRM_ENABLED, H1_TF_SEC, H1_CANDLES_LOOKBACK,
    H1_EMA_FAST, H1_EMA_SLOW, H1_FETCH_TIMEOUT_SEC,
    M1_MICRO_CONFIRM_ENABLED, CANDLE_FETCH_TIMEOUT_SEC,
    CANDLE_FETCH_1M_TIMEOUT_SEC, SCAN_MAX_ASSETS_PER_CYCLE,
)
