"""Trading timing, candle and payout configuration.

Compatibility surface: values remain owned by the legacy ``config`` module
until all consumers are migrated. Do not redefine values here.
"""
from config import (
    TF_5M, TF_15M, TF_1M, CANDLES_LOOKBACK, HISTORICAL_M15_COUNT,
    MIN_CONSOLIDATION_BARS, MAX_RANGE_PCT, TOUCH_TOLERANCE_PCT,
    MAX_CONSOLIDATION_MIN, MIN_PAYOUT, DURATION_SEC,
    MULTI_DURATION_DATA_COLLECTION, MULTI_DURATION_SECS,
    MULTI_DURATION_MASSANIELLO_PRIMARY_SEC, MULTI_DURATION_PARALLEL,
    MULTI_DURATION_IGNORE_SESSION_BLOCKS, SCAN_INTERVAL_SEC,
    MAX_CONCURRENT_TRADES, COOLDOWN_BETWEEN_ENTRIES,
    ENTRY_SYNC_TO_CANDLE, ENTRY_MAX_LAG_SEC, ENTRY_REJECT_LAST_SEC,
    ENTRY_SYNC_TF_SEC, FAST_ENTRY, FAST_ENTRY_TF_SEC,
    ALIGN_SCAN_TO_CANDLE, SCAN_LEAD_SEC,
)
