"""Constantes operativas del bot de consolidación Quotex."""
from __future__ import annotations

import os
from datetime import timedelta, timezone
from pathlib import Path

TF_5M = 300
TF_1M = 60
CANDLES_LOOKBACK = 55
MIN_CONSOLIDATION_BARS = 12
MAX_RANGE_PCT = 0.003
TOUCH_TOLERANCE_PCT = 0.00035
MAX_CONSOLIDATION_MIN = 0
MIN_PAYOUT = 80
DURATION_SEC = 30
SCAN_INTERVAL_SEC = 60
CONNECT_RETRIES = 3
MAX_CONCURRENT_TRADES = 1
COOLDOWN_BETWEEN_ENTRIES = 30
ENTRY_SYNC_TO_CANDLE = True
ENTRY_MAX_LAG_SEC = 0.3
ENTRY_REJECT_LAST_SEC = 2.0
ALIGN_SCAN_TO_CANDLE = False
SCAN_LEAD_SEC = 35.0
MAX_LOSS_SESSION = 0.20

CYCLE_MAX_OPERATIONS = 5
CYCLE_TARGET_WINS = 3
CYCLE_TARGET_PROFIT_PCT = 0.10

MASSANIELLO_OPERATIONS = 5
MASSANIELLO_EXPECTED_WINS = 3
SESSION_MAX_MIN = 60
RISK_MANAGER = "massaniello"

USE_DYNAMIC_ATR_RANGE = True
ATR_PERIOD = 14
ATR_RANGE_FACTOR = 1.35
MIN_DYNAMIC_RANGE_PCT = 0.0015
MAX_DYNAMIC_RANGE_PCT = 0.0150

H1_CONFIRM_ENABLED = True
H1_TF_SEC = 3600
H1_CANDLES_LOOKBACK = 80
H1_EMA_FAST = 20
H1_EMA_SLOW = 50
H1_FETCH_TIMEOUT_SEC = 12.0
CANDLE_FETCH_TIMEOUT_SEC = 8.0
CANDLE_FETCH_1M_TIMEOUT_SEC = 12.0
FETCH_RETRIES = 2
FETCH_RETRY_BACKOFF_SEC = 0.35
ORDER_SEND_RETRIES = 1
RECONNECT_TIMEOUT_SEC = 12.0
SCAN_MAX_ASSETS_PER_CYCLE = 40
SCAN_PROGRESS_EVERY = 10

CANDLE_FETCH_CONCURRENCY = 2
CANDLE_CACHE_TTL_SEC = 300
CANDLE_CACHE_INCREMENTAL_COUNT = 8
HEALTHCHECK_RECONNECT_RETRIES = 2
CF_403_BACKOFF_SEC = 8.0

VOLUME_MULTIPLIER = 1.2
VOLUME_LOOKBACK = 10
REBOUND_MIN_STRENGTH_CALL = 0.50
REBOUND_MIN_STRENGTH_PUT = 0.65
REJECTION_CANDLE_MIN_BODY = 0.40
REJECTION_PUT_MIN_UPPER_WICK = 0.30
ZONE_AGE_REBOUND_MIN = 20
ZONE_AGE_BREAKOUT_MIN = 8
ZONE_MIN_AGE_MIN = ZONE_AGE_REBOUND_MIN
FORCE_EXECUTE_STRONG_BREAKOUT = True
GREYLIST_ASSETS = {"USDDZD_otc"}
PATTERN_PUT_BLACKLIST = {"bearish_engulfing"}
STRICT_PATTERN_CHECK = True

ADAPTIVE_THRESHOLD_BASE = 65
ADAPTIVE_THRESHOLD_LOW = 62
ADAPTIVE_THRESHOLD_HIGH = 68
ADAPTIVE_THRESHOLD_WINDOW_SCANS = 10

ASSET_LOSS_STREAK_LIMIT = 3
ASSET_BLACKLIST_DURATION_MIN = 60
MAX_CONSECUTIVE_ENTRIES_PER_ASSET = 2

ORDER_BLOCK_LOOKBACK = 50
ORDER_BLOCK_MAX_PER_SIDE = 3
ORDER_BLOCK_MIN_MOVE_PCT = 0.002
ORDER_BLOCK_TOUCH_TOLERANCE_PCT = 0.0003
ORDER_BLOCK_TF_SEC = 180
ORDER_BLOCK_CANDLES = 55

MA_LOOKBACK_CANDLES = 60
MA_FAST_PERIOD = 35
MA_SLOW_PERIOD = 50
MA_FLAT_DELTA_PCT = 0.0005
DRY_RUN_VERBOSE = True

EMAIL = os.environ.get("QUOTEX_EMAIL", "")
PASSWORD = os.environ.get("QUOTEX_PASSWORD", "")

BROKER_TZ = timezone(timedelta(hours=-3))
BROKER_TZ_LABEL = "UTC-3"

MIN_ORDER_AMOUNT = 1.00
MARTIN_MAX_PCT_BALANCE = 0.20
MARTIN_MAX_ATTEMPTS_SESSION = 2
MARTIN_LOW_BALANCE_THRESHOLD = 100.0
MARTIN_MAX_ATTEMPTS_LOW_BALANCE = 3
PENDING_RECONCILE_AGE_MIN = 15.0
MARTIN_MONITOR_INTERVAL_SEC = 10.0
MARTIN_ALERT_PCT = 0.0005
MARTIN_LIVE_WINDOW_MIN_SEC = 30.0
MARTIN_LIVE_WINDOW_MAX_SEC = 60.0
MARTIN_RESOLVE_GRACE_SEC = 5.0
MARTIN_RESOLVE_TIMEOUT_SEC = 8.0
MARTIN_RESOLVE_RETRY_SEC = 5.0
MARTIN_RESOLVE_MAX_ATTEMPTS = 3

STRAT_B_CAN_TRADE = True
STRAT_B_DURATION_SEC = 30
STRAT_B_MIN_CONFIDENCE = 0.70
STRAT_B_MIN_CONFIDENCE_EARLY = 0.62
STRAT_B_ALLOW_WYCKOFF_EARLY = True
STRAT_B_LOG_TOP_N = 3
STRAT_B_PREVIEW_MIN_CONF = 0.45

BROKEN_CAPTURE_DIR = Path(__file__).resolve().parent.parent / "data" / "vela_ops"
BROKEN_FOLLOWUP_DELAY_SEC = 15 * 60
BROKEN_FOLLOWUP_1M_COUNT = 40

# Compatibilidad con main.py (_apply_runtime_config)
AMOUNT_INITIAL = 1.0
AMOUNT_MARTIN = 3.0